name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Firefox releases
        # https://download-installer.cdn.mozilla.net/pub/firefox/releases/
        # Chrome versions
        # https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
        firefox_version: ["91.9.1esr"]
        chrome_version: ["103.0.5060.114"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Store env vars
        id: step_one
        run: |
          echo "short_sha=$(git rev-parse --short=7 $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Build standalone image
        uses: redhat-actions/buildah-build@v2
        with:
          image: quay.io/redhatqe/selenium-standalone
          tags: latest ${{ env.short_sha }} ff_${{ matrix.firefox_version }}_chrome_${{ matrix.chrome_version }}
          dockerfiles: standalone/Dockerfile
          context: standalone
          oci: true
          build-args: |
            CHROME_VERSION=${{ matrix.chrome_version }}
            FIREFOX_VERSION=${{ matrix.firefox_version }}
      - name: Push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: selenium-standalone
          tags: latest ${{ env.short_sha }} ff_${{ matrix.firefox_version }}_chrome_${{ matrix.chrome_version }}
          registry: quay.io/redhatqe
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}

